### ISSUE TITLE
Installing redis on Apple M2 leads to compiler errors

### ISSUE THREAD

**Issue by korey-enright** [smashedtoatoms/asdf-redis#13]
**Describe the bug**

Running `asdf install redis 6.2.6` leads to various compiler errors, including:

```
replication.c:1312:31: error: variable has incomplete type 'struct stat64'
            struct redis_stat buf;
                              ^
replication.c:1312:20: note: forward declaration of 'struct stat64'
            struct redis_stat buf;
                   ^
./config.h:45:20: note: expanded from macro 'redis_stat'
#define redis_stat stat64
                   ^
replication.c:1359:21: error: call to undeclared function 'fstat64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                    redis_fstat(slave->repldbfd,&buf) == -1) {
                    ^
./config.h:44:21: note: expanded from macro 'redis_fstat'
#define redis_fstat fstat64
```

**Additional Context**

Currently using version 14 of XCode developer tools, on Ventura 13.5 (22G74). Brand new M2 MacBook Pro.

**Comment by Jesse-Cameron** [comment]
Heya @korey-enright , I believe that this is an issue the redis build not the plugin. See similar here: https://github.com/redis/redis/issues/12585

**Comment by stanhu** [comment]
https://github.com/smashedtoatoms/asdf-redis/pull/14 would help here. You could then do:

```shell
REDIS_APPLY_PATCHES=https://patch-diff.githubusercontent.com/raw/redis/redis/pull/12611.diff asdf install redis 6.2.6
```

**Comment by stanhu** [comment]
I think we can close this issue since this is an upstream Redis issue. The command above is a workaround for now.

**Comment by smashedtoatoms** [comment]
Thanks for taking care of this, @stanhu!
