### ISSUE TITLE
bug: Can't install redis 7.0.14 on Mac

### ISSUE THREAD

**Issue by tarikrital** [smashedtoatoms/asdf-redis#15]
### Describe the Bug

Welcome, I was able to install the version 7.2.3 on Mac but with 7.0.14 it fails.

### Steps to Reproduce

1. Open Mac terminal
2. asdf install redis 7.0.14

### Expected Behaviour

The installation works with success.

### Actual Behaviour

```
** Resuming transfer from byte position 2994188
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   206  100   206    0     0    140      0  0:00:01  0:00:01 --:--:--   140
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
    LINK redis-server
clang: error: no such file or directory: '../deps/lua/src/liblua.a'
clang: error: no such file or directory: '../deps/hdr_histogram/libhdrhistogram.a'
make[1]: *** [redis-server] Error 1
make: *** [install] Error 2

```

### Environment

```shell
OS:
Darwin 192.168.1.9 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.7.1 (x86_64-apple-darwin19.0)

BASH VERSION:
3.2.57(1)-release

ASDF VERSION:
v0.13.1-0586b37

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/Users/wpplumber/.asdf
ASDF_DIR=/usr/local/opt/asdf/libexec
ASDF_CONFIG_FILE=/Users/wpplumber/.asdfrc

ASDF INSTALLED PLUGINS:
gitleaks                     https://github.com/jmcvetta/asdf-gitleaks.git main 0cc0d7e
golang                       https://github.com/asdf-community/asdf-golang.git master 33b1f6d
minio                        https://github.com/aeons/asdf-minio.git master 113b19d
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 150ec5d
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git master 55111bf
redis                        https://github.com/smashedtoatoms/asdf-redis.git master beedc89
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 3035a4a
rust                         https://github.com/code-lever/asdf-rust.git master 95acf4f
shellcheck                   https://github.com/luizm/asdf-shellcheck.git master b160a52
vale                         https://github.com/pdemagny/asdf-vale main 9a3b1c0
yarn                         https://github.com/twuni/asdf-yarn.git main 376c540
```

**Comment by smashedtoatoms** [comment]
I am unable to replicate this issue on an M2 air running Sonoma. Both install fine for me. Missing .a files usually mean a compile step didn't run in an earlier part of the build, and the artifacts (liblua.a and libhdrhistogram.a) were not created. I am not sure why that might have happened though. I saw that you opened an issue with Redis.  If they make a suggestion, I will see if I can implement it on this side.  All this plugin really does is compile from source and use asdf to put it in path.

**Comment by smashedtoatoms** [comment]
Oh, never mind, I see they just passed it on to me.  If you download that version and compile it from source, do you get the same result?

**Comment by smashedtoatoms** [comment]
Just as a place to start, I'd ask that you nuke the redis install on asdf, re-install it, and re-run the install.  To be doubly sure, run `mktemp -d` and note everything up to and including the `/T/`.  Once you do that, run rm -rf <path_up_to_and_including_T>/redis-7*.  That will nuke all of the previous build attempts and force a re-download and rebuild from scratch.  It will all look something like this:
```
➜  mktemp -d
/var/folders/2z/gd010d9134x2vjk_b6lcbbvc0000gn/T/tmp.AdSfu4syNT
➜  rm -rf /var/folders/2z/gd010d9134x2vjk_b6lcbbvc0000gn/T/redis-7.*
➜  asdf plugin remove redis
➜  asdf plugin add redis
➜  asdf install redis 7.2.3
```

**Comment by tarikrital** [comment]
After a reboot the install passed!

Thank you, @smashedtoatoms
