### ISSUE TITLE
Add `getting started` to README

### ISSUE THREAD

**Issue by meyercm** [smashedtoatoms/asdf-redis#2]
Just installed asdf-redis, and have no idea how to start up the redis server.  A paragraph of getting started info would go a long way for new users.

**Comment by smashedtoatoms** [comment]
Sorry, I just saw this.  I created this basically for myself, and I manually start it in a tmux session on the default port.  I figured everyone would have their own workflow, so I never specified, which was probably kind of dumb of me.  In any case, here is what I would do.

1. Open up a terminal and run `redis-server`.  This will get it running on the standard port (6379)
1. Open another terminal and run `redis-cli`.   This will open the redis cli so you can manually set, get, and delete keys.  For example: 
```sh
~ % redis-cli
127.0.0.1:6379> set someKey "boomdiggity"
OK
127.0.0.1:6379> get someKey
"boomdiggity"
```

At this point, you should be good to go.  Just kill it when you don't need it anymore.  All sdks should be able to run against 127.0.0.1:6379.  Hope that helps.

**Comment by meyercm** [comment]
Thanks for the reply.  I'm not sure why I had problems right at the start, but `redis-server` failed (I don't remember the error anymore), and I just assumed I was using the package incorrectly- but later (after posting the issue), everything seemed to work fine. Thanks for providing this plugin!
